language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t leonardoramosc/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true leonardoramosc/docker-react npm run test -- --coverage

